package presenters;


public enum Events {
    EXIT, EDIT_PROCESS, DELETE_PROCESS, ADD_PROCESS, ACCEPT_EDIT_PROCESS, CANCEL_EDIT_PROCESS,
    ACCEPT_ADD_PROCESS, CANCEL_ADD_PROCESS, ACCEPT_ADD_PARTITION, ACCEPT_EDIT_PARTITION, 
    CANCEL_ADD_PARTITION, CANCEL_EDIT_PARTITION, ADD_PARTITION, EDIT_PARTITION, DELETE_PARTITION,
    INIT_SIMULATION, NEW_SIMULATION
}
